# Generated by Django 6.0.3 on 2026-03-03 19:06

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อสัตว์เลี้ยง')),
                ('description', models.TextField(verbose_name='รายละเอียด/ลักษณะ')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='ละติจูด')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='ลองจิจูด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_images/')),
                ('feature_vector', pgvector.django.vector.VectorField(blank=True, dimensions=2048, null=True)),
                ('pet_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pet_core.petpost')),
            ],
        ),
    ]
