# Generated by Django 6.0.3 on 2026-03-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0002_petpost_age_petpost_breed_petpost_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpost',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='petpost',
            name='found_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petpost',
            name='found_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petpost',
            name='lost_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petpost',
            name='lost_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petpost',
            name='microchip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='petpost',
            name='situation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petpost',
            name='social_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียด/ลักษณะ'),
        ),
    ]
