# Generated by Django 6.0.3 on 2026-03-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0003_petpost_contact_email_petpost_found_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'ประกาศสัตว์เลี้ยง', 'verbose_name_plural': 'ประกาศสัตว์เลี้ยงทั้งหมด'},
        ),
        migrations.AddField(
            model_name='petpost',
            name='status',
            field=models.CharField(choices=[('active', 'กำลังตามหา/กำลังหาเจ้าของ'), ('resolved', 'เจอแล้ว/ส่งคืนแล้ว')], default='active', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='petpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='อายุ'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='สายพันธุ์'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='สี'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลผู้ติดต่อ'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อผู้ติดต่อ'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='found_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่พบ'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='found_time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาที่พบ'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ตัวผู้'), ('F', 'ตัวเมีย'), ('U', 'ไม่ระบุ/ไม่แน่ใจ')], max_length=20, null=True, verbose_name='เพศ'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ละติจูด'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สถานที่ (ชื่อเรียก)'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ลองจิจูด'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='lost_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่หาย'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='lost_time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาที่หาย'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='microchip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขไมโครชิป'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='pet_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ประเภทสัตว์ (เช่น สุนัข, แมว)'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='post_type',
            field=models.CharField(choices=[('lost', 'หาย'), ('found', 'พบ')], default='lost', max_length=10, verbose_name='ประเภทประกาศ'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='situation',
            field=models.TextField(blank=True, null=True, verbose_name='สถานการณ์ตอนที่หาย/พบ'),
        ),
        migrations.AlterField(
            model_name='petpost',
            name='social_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ลิงก์โซเชียลมีเดีย'),
        ),
    ]
