# Generated by Django 6.0.3 on 2026-03-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0004_alter_petpost_options_petpost_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='รูปภาพหลัก'),
        ),
        migrations.AlterModelTable(
            name='petimage',
            table='pet_core_petimage',
        ),
        migrations.AlterModelTable(
            name='petpost',
            table='pet_core_petpost',
        ),
    ]
