# Generated by Django 5.0.14 on 2026-05-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0016_remove_scraped_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(help_text='กด Enter 1 ครั้ง = ขึ้นบรรทัดใหม่ · กด Enter 2 ครั้ง = ย่อหน้าใหม่', verbose_name='เนื้อหา'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='source_name',
            field=models.CharField(blank=True, help_text='เช่น: สัตวแพทย์ ดร.สมชาย / เว็บไซต์ petmd.com / วารสารสัตวแพทย์ไทย', max_length=200, verbose_name='แหล่งที่มา (ชื่อ)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_link',
            field=models.URLField(blank=True, help_text='วางลิงก์สินค้าจาก Shopee / Lazada / Facebook ฯลฯ<br>✅ <b>ใส่ได้เลยทุกแบบ</b> — ระบบจะตัด tracking token (sp_atk, utm_* ฯลฯ) ออกให้อัตโนมัติ<br>ตัวอย่าง Shopee: <code>https://shopee.co.th/product-name-i.123456.789</code>', max_length=2000, verbose_name='ลิงก์ไปร้านค้า'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ไม่ต้องใส่ก็ได้ถ้าต้องการให้ผู้ใช้ไปดูราคาที่หน้าร้าน', max_digits=10, null=True, verbose_name='ราคาตั้ง (บาท) — ไม่บังคับ'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
