# Generated by Django 5.0.14 on 2026-05-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0017_align_product_and_blog_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', '-published_at'], name='blog_published_at_idx'),
        ),
    ]
