# Generated by Django 5.0.14 on 2026-05-11 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_core', '0018_harden_security_and_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('post_create', 'สร้างประกาศ'), ('post_edit', 'แก้ไขประกาศ'), ('post_delete', 'ลบประกาศ'), ('post_resolve', 'ปิดประกาศ'), ('comment_create', 'เพิ่มความคิดเห็น'), ('account_delete', 'ลบบัญชี')], db_index=True, max_length=40)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'db_table': 'pet_core_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='audit_action_created_idx'), models.Index(fields=['user', '-created_at'], name='audit_user_created_idx')],
            },
        ),
    ]
